name: scout_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_bloc: ^8.0.0
  strapi_converter:
    path: "./packages/strapi_converter"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true
